import os
from image_gen import generate_thumbnail

# Ensure output directory exists
if not os.path.exists("output"):
    os.makedirs("output")

print("Generating test image locally...")
try:
    # Override the output path in generate_thumbnail to use our local output folder
    # Actually generate_thumbnail saves to static/generated by default.
    # We can just copy it or let it save there and print the path.
    
    path = generate_thumbnail("A cute cat eating a burger")
    print(f"Success! Image saved to: {path}")
    
    # Copy to output folder for user visibility
    import shutil
    filename = os.path.basename(path)
    dest = os.path.join("output", filename)
    shutil.copy(path, dest)
    print(f"Copied to: {dest}")
    
except Exception as e:
    print(f"Error: {e}")
